### ISSUE TITLE
Docker Compose under a different location is not recognized

### ISSUE THREAD

**Issue by AetherUnbound** [rafalp/misago_docker#82]
I see that docker-compose is required for installing: [line in file](https://github.com/rafalp/misago_docker/blob/master/appctl#L19). This assumes that the docker compose binary is located at `/usr/local/bin/docker-compose`. I installed docker-compose using the [instructions provided by DigitalOcean](https://www.digitalocean.com/community/tutorials/how-to-install-docker-compose-on-ubuntu-16-04), and this put the docker-compose binary in `/usr/bin/docker-compose`.

```bash
misago@ubuntu-dataswamp-forum:~/misago_docker$ which docker-compose
/usr/bin/docker-compose
```

Would it be possible to use `$(which docker-compose)` to find where docker compose is?

ALso, let me say that the infrastructure and documentation you have for this project is _so awesome_! I can't tell y'all how much I appreciate it :smile: I spent 10 hours trying to set up a different solution that had some really outdated documentation - I'm glad you've made this so easy.

**Comment by rafalp** [comment]
For my curiosity: why did you have to install docker-compose on your own? Is that a pre-existing VPS? Our installation guide directs folk to the pre-made VPS image that has docker preinstalled when starting Misago site. 🤔

**Comment by AetherUnbound** [comment]
Ah, I actually purchased a DigitalOcean Ubuntu droplet. I'm not sure if that's different from a VPS, but I guess that might come a little bit more bare-bones. I was attempting to set up a different solution but ended up forgoing that for Misago (and I'm so glad I did, I got the site set up in minutes!). Beyond the docker-compose stuff, the setup was quite easy!
