### ISSUE TITLE
Version without automated nginx proxy

### ISSUE THREAD

**Issue by twendt97** [rafalp/misago_docker#93]
Hello first of all i want to thank you for the great work you did here it is really a fantastic peace of software and it saved me a lot of time.

On the other hand I want to embed a forum into an architecture containing a mail server a nextcloud and a wordpress blog so I had to customize this version because i use a static reverse proxy (the one from linuxserver/letsencrypt). It would be great, if you provide a version with only a webserver proxying the http requests to the uwsgi server. I got this setup up and running if you want I can provide you my solution.

**Comment by rafalp** [comment]
I'm afraid I don't have resources to do this, but if somebody else wants to maintain their own repo providing this, they are free to do so.

Thanks anyway!
