### ISSUE TITLE
Incorrect TZ results in silent failure of first time setup.

### ISSUE THREAD

**Issue by GavinThomas1192** [rafalp/misago_docker#94]
Hello, 

Let me first say, I think this tutorial is absolutely awesome, and the setup docs are very detailed and appreciated. 

I went through my first time setup of a production server through digital ocean here. https://misago.gitbook.io/docs/setup/misago

The first time I went through I inputted the incorrect TZ format, I put 'america/los_angeles' instead of America/Los_Angeles. The python script did alert me of an invalid tz but the rest of the docker setup continued.

After it finished, the terminal prompts said all was good to go, and I could visit mysite.com/admincp, however this tz failure cause the database setup to fail and not finish. It did not ask me for my super user info. 

This caused the live site to fail 'password authentication failed for user xxxxxxmisago'. It took a while to figure out the TZ failure caused an incorrect setup of the DB. 

I destroyed my droplett and started over, with the correct TZ the first time, and the setup asked for a superuser, and all is well. 

I wish I had more SS, but I didn't know what the bug was until I have started over. Maybe we could layout tz formats need to be EXACT.

**Comment by rafalp** [comment]
Woah, you may actually have worked out the cause behind the issue that was reported quite a few times already!

Thank you for reporting this!
