### ISSUE TITLE
daily backup did not generate database.sql file in the backup folder 

### ISSUE THREAD

**Issue by Jiansiyu** [rafalp/misago_docker#98]
Thank you very much for the amazing project. 

I noticed one issue. the auto daily backups in the backups folder. The database backup did not show in the tar.gz file.

**Comment by rafalp** [comment]
That's weird. It always worked for me (until it ran out of disk space for backups). Are you sure there's enough space?

**Comment by Jiansiyu** [comment]
There is only 37% of the space is used.  It is weird. All the manual and Upgrade backups are normal. 

![image](https://user-images.githubusercontent.com/16512360/139597791-614a3ebb-cd5e-4aab-9d9e-2c879d7b8513.png)

**Comment by rafalp** [comment]
I've checked random daily backup and indeed its missing database.sql

**Comment by rafalp** [comment]
Ok, I understand what's happening here.

Daily backup is done with crontab:

```
0 1 * * * cd /root/misago_docker && ./appctl daily_backup
```

`./appctl` tries to do `docker compose run --rm misago ./.run backup_db` which fails for cron user.

**Comment by rafalp** [comment]
I've did a quick test and got following error:

```
./appctl: line 333: run: command not found
```
